apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: spring-music
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dlemus/tap-spring-music
      ref:
        branch: master
        #  serviceClaims:
        #    - name: db
        #      ref:
        #        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        #        kind: ClassClaim
        #        name: mysql-1
